site:
  name: "TellusionLab"
#  outage_emails:
#    - email: "ap@andrewprendergast.com"
#    - email: sfgdfgdfg@sendmonitoringalert.com
  outage_webhooks:

#    - endpoint_url: http://irmsg.vizdynamics.com/OsborneStInception.-1/
#      request_method: GET
#      request_encoding: URL
#      request_prefix: "HELLO "
#      request_suffix: "WORLD "

    - endpoint_url: https://api.pushover.net/1/messages.json
      request_method: POST
      request_encoding: URL
      request_prefix: token=a3xbjwbeekmyiq2n54prtm9p77uf1c&user=uc1ga5ckhazyzvi2g348kuzj3tbgwc&sound=alien&priority=1&message=

  max_retries: 1 # 1 = enable realtime monitoring
  max_threads: 20 # >1 = enable realtime monitoring
  max_try_secs: 10

  check_every_n_secs: 60
  notify_every_n_secs: 3600
  after_every_n_notifications: 8

monitors:

  - type: ping
    name: tellusion-gw
    address: "192.168.68.1"
    heartbeat_url: "http://google.com/"

  - type: ping
    name: tellusion-fw
    address: "192.168.1.1"
    heartbeat_url: "http://google.com/"

  - type: ping
    name: "Inception t4000"
    address: "192.168.1.22"
    heartbeat_url: "http://excite.com/"
    notify_every_n_secs: 43200
    after_every_n_notifications: 6

  - type: http
    name: in07724215
    address: "http://inception.tellusion.com/Login?oldUrl=Index"
    expect: "System Name: <b>TellusionLab</b>"
    heartbeat_url: "http://google.com/"
    notify_every_n_secs: 43200
    after_every_n_notifications: 6

  - type: http
    name: nvr0
    address: https://nvr0.tellusion.com/api/system
    expect: "nvr0"
    ssl_fingerprint: 0b06d8b395a4e8bf974a5ba5ab203e743979c5ea0fbb1e348c8683c6eb7f9498
    heartbeat_url: https://plus.site24x7.com/hb/1a428ecc2a4753a5eaf43a9a4fd121e8/nvr0
    heartbeat_every_n_secs: 300

#  - type: http
#    name: "Study Desk"
#    address: https://192.168.1.33/settings/config.json
#    expect: CAMERA
#    ssl_fingerprint: ae837c1bcb7e8515a9f30066495a614b2ce506fa4618c56cae72a7c5906f6c1e
#    heartbeat_url: https://plus.site24x7.com/hb/1a428ecc2a4753a5eaf43a9a4fd121e8/StudyDeskCam
#    heartbeat_every_n_secs: 300

  - type: http
    name: "Lounge Temp"
    address: https://192.168.1.9/settings/config.json
    expect: CAMERA
    ssl_fingerprint: 74903b1fcd7c476838b8eaa27c313c2c9de52268bc350f1145da77fe5e3a71f8
    heartbeat_url: https://plus.site24x7.com/hb/1a428ecc2a4753a5eaf43a9a4fd121e8/LoungeTempCam
    heartbeat_every_n_secs: 300

  - type: http
    name: nvr1
    address: https://nvr1.tellusion.com/api/system
    expect: "nvr1"
    ssl_fingerprint: d370d882ab9c2f9ee311c64ee6c9e4ebbc621cd4340519c11f9397009c7268fd
    heartbeat_url: https://plus.site24x7.com/hb/1a428ecc2a4753a5eaf43a9a4fd121e8/nvr1
    heartbeat_every_n_secs: 300

  - type: http
    name: nvr2
    address: https://nvr2.tellusion.com/api/system
    expect: "nvr2"
    ssl_fingerprint: e85260e8f8e85629cfa4d023ea0ae8dd3ce8ccc0040b054a4753c2a5ab269296
    heartbeat_url: https://plus.site24x7.com/hb/1a428ecc2a4753a5eaf43a9a4fd121e8/nvr2
    heartbeat_every_n_secs: 300

  - type: http
    name: "Front Piazza Entryway"
    address: https://192.168.1.31/settings/config.json
    expect: CAMERA
    ssl_fingerprint: 880e1c4e19468c9953454afb8904b0886c160a060a01cccd2a36a8aeb063890d
    heartbeat_url: https://plus.site24x7.com/hb/1a428ecc2a4753a5eaf43a9a4fd121e8/FrontPiazzaEntrywayCam
    heartbeat_every_n_secs: 300

  - type: http
    name: "Front Piazza Carpark"
    address: https://192.168.1.32/settings/config.json
    expect: CAMERA
    ssl_fingerprint: 256a810b67d1892de1f4698d3f925f21837dc251fd738ea46795dee77ee82a89
    heartbeat_url: https://plus.site24x7.com/hb/1a428ecc2a4753a5eaf43a9a4fd121e8/FrontPiazzaCarparkCam
    heartbeat_every_n_secs: 300

  - type: ping
    name: "USW Pro 24 PoE"
    address: 192.168.1.6

  - type: snmp
    name: "switch"
    address: snmp://192.168.1.6
    community: TellusionLab
    percentile: 95

  - type: ports
    name: "switch-ports"
    address: snmp://192.168.1.6
    community: TellusionLab

  - type: snmp
    name: "nvr1snmp"
    address: snmp://nvr1.tellusion.com
    community: TellusionLab
    percentile: 98
    
  - type: port
    name: "switch-uplink"
    address: snmp://192.168.1.6
    community: TellusionLab
    check_every_n_secs: 10
    notify_every_n_secs: 60
    after_every_n_notifications: 6
    port: 1
    mac: 18:E8:29:45:F8:F7
    always_up: yes

  - type: port
    name: "switch-port14"
    address: snmp://192.168.1.6
    community: TellusionLab
    check_every_n_secs: 10
    notify_every_n_secs: 60
    after_every_n_notifications: 6
    port: 14
    mac: F0:23:B9:EC:67:FC
    always_up: yes

  - type: snmp
    name: debmon
    address: "snmp://127.0.0.1"
    community: "TellusionLab"
    check_every_n_secs: 60

#  - type: ping
#    name: "DNS Host A"
#    address: 192.168.1.6
#    display: no
#
#  - type: ping
#    name: "DNS Host B"
#    address: 192.168.1.199
#    display: no


